## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

%define po_package gnome-session

Name:           gnome-session
Version:        51~rc
Release:        %autorelease
Summary:        GNOME session manager

License:        GPL-2.0-or-later
URL:            https://gitlab.gnome.org/GNOME/gnome-session
Source:         https://download.gnome.org/sources/%{name}/%{gnome_major_version}/%{name}-%{gnome_tarball_version}.tar.xz

%gnome_check_version

# For https://fedoraproject.org/w/index.php?title=Changes/HiddenGrubMenu
# This should go upstream once systemd has a generic interface for this
Patch:          0001-Fedora-Set-grub-boot-flags-on-shutdown-reboot.patch

BuildRequires:  meson
BuildRequires:  gcc
BuildRequires:  pkgconfig(gnome-desktop-4)
BuildRequires:  pkgconfig(libsystemd)
BuildRequires:  pkgconfig(systemd)

BuildRequires:  gettext
BuildRequires:  xmlto
BuildRequires:  /usr/bin/xsltproc

# an artificial requires to make sure we get dconf, for now
Requires: dconf

Requires: gsettings-desktop-schemas >= 0.1.7

Requires: dbus

Conflicts: gnome-desktop3 < 44.4-2
Conflicts: shared-mime-info < 2.0-4
Requires: shared-mime-info

# https://github.com/containers/composefs/pull/229#issuecomment-1838735764
%if 0%{?rhel} >= 10
ExcludeArch:    %{ix86}
%endif


%description
gnome-session manages a GNOME desktop or GDM login session. It starts up
the other core GNOME components and handles logout and saving the session.

%package wayland-session
Summary: Desktop file for wayland based gnome session
Requires: %{name}%{?_isa} = %{version}-%{release}
Requires: xorg-x11-server-Xwayland%{?_isa} >= 1.20.99.1
Requires: gnome-shell
Obsoletes: gnome-session-xsession < %{version}-%{release}

%description wayland-session
Desktop file to add GNOME on wayland to display manager session menu.

%prep
%autosetup -p1 -n %{name}-%{gnome_tarball_version}

%build
%meson
%meson_build

%install
%meson_install

%find_lang %{po_package}

%ldconfig_scriptlets

%files wayland-session
%{_datadir}/wayland-sessions/*

%files -f %{po_package}.lang
%doc NEWS
%license COPYING
%{_bindir}/gnome-session*
%{_libexecdir}/gnome-session-ctl
%{_libexecdir}/gnome-session-init-worker
%{_libexecdir}/gnome-session-service
%{_mandir}/man1/gnome-session*1.*
%{_datadir}/applications/gnome-mimeapps.list
%{_datadir}/gnome-session/
%dir %{_datadir}/xdg-desktop-portal
%{_datadir}/xdg-desktop-portal/gnome-portals.conf
%{_datadir}/doc/gnome-session/html
%{_datadir}/glib-2.0/schemas/org.gnome.SessionManager.gschema.xml
%{_userunitdir}/gnome-session*
%{_userunitdir}/app-flatpak-.scope.d/override.conf
%{_userunitdir}/app-gnome-.scope.d/override.conf

%changelog
## START: Generated by rpmautospec
* Wed Sep 02 2026 Milan Crha <mcrha@redhat.com> - 51~rc-1
- Update to 51.rc

* Wed Aug 05 2026 Jan Grulich <jgrulich@redhat.com> - 51~beta-1
- Update to 51.beta

* Thu Jul 16 2026 Fedora Release Engineering <releng@fedoraproject.org> - 51~alpha-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_45_Mass_Rebuild

* Wed Jul 01 2026 Milan Crha <mcrha@redhat.com> - 51~alpha-1
- Update to 51.alpha

* Tue Jun 30 2026 Milan Crha <mcrha@redhat.com> - 50.1-3
- Rebuild for new gnome-desktop4

* Fri May 29 2026 nmontero <nmontero@redhat.com> - 50.1-1
- Update to 50.1

* Wed Mar 25 2026 Jan Grulich <jgrulich@redhat.com> - 50.0-3
- Add configuration for release-monitoring

* Mon Mar 16 2026 Milan Crha <mcrha@redhat.com> - 50.0-1
- Update to 50.0

* Tue Mar 03 2026 Jan Grulich <jgrulich@redhat.com> - 50~rc-1
- Update to 50.rc

* Mon Mar 02 2026 Jan Grulich <jgrulich@redhat.com> - 50~beta-4
- Packit: drop upstream_project_url and rely on release-monitoring only

* Wed Feb 25 2026 Jan Grulich <jgrulich@redhat.com> - 50~beta-3
- Packit: drop fast_forward_merge_into as current stable branches diverge

* Tue Feb 24 2026 Jan Grulich <jgrulich@redhat.com> - 50~beta-2
- Onboard to Packit for stable Fedora branches

* Mon Feb 09 2026 Jan Grulich <jgrulich@redhat.com> - 50~beta-1
- Update to 50.beta

* Mon Jan 26 2026 Jan Horak <jhorak@redhat.com> - 50~alpha-1
- Update to 50~alpha

* Fri Jan 16 2026 Fedora Release Engineering <releng@fedoraproject.org> - 49.2-14
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Thu Dec 18 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-13
- Fixup mimeapps.list for GNOME Disks

* Wed Dec 17 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-12
- Add mimeapps-related Conflicts and Requires

* Wed Dec 17 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-11
- Fix RPM build warning

* Wed Dec 17 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-10
- Ship gnome-mimeapps.list

* Wed Dec 17 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-9
- Drop unused GTK4 and json-glib dependencies

* Tue Dec 16 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-8
- Drop gnome-control-center-filesystem dependency

* Tue Dec 16 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-7
- Drop system-logos

* Tue Dec 16 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-6
- Drop usermode

* Tue Dec 16 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-5
- Drop X11 dependencies

* Tue Dec 16 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-4
- Drop OpenGL dependencies

* Tue Dec 16 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.2-3
- Reintroduce GRUB bootflags patch

* Tue Nov 25 2025 Debarshi Ray <rishi@fedoraproject.org> - 49.2-2
- Stop referring to gnome-control-center as control-center

* Tue Nov 25 2025 Debarshi Ray <rishi@fedoraproject.org> - 49.2-1
- Update to 49.2

* Mon Oct 13 2025 Petr Schindler <pschindl@redhat.com> - 49.1-1
- Update to 49.1

* Tue Sep 16 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 49.0-1
- Update to 49.0

* Thu Sep 04 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 49~rc-1
- Update to 49.rc

* Thu Aug 07 2025 nmontero <nmontero@redhat.com> - 49~beta-1
- Update to 49~beta

* Wed Jul 23 2025 Fedora Release Engineering <releng@fedoraproject.org> - 49~alpha.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Fri Jul 04 2025 Milan Crha <mcrha@redhat.com> - 49~alpha.1-1
- Update to 49.alpha.1

* Tue Jun 17 2025 Carlos Garnacho <cgarnach@redhat.com> - 49~alpha.0-1
- Update to 49~alpha.0

* Mon Jun 02 2025 Adam Williamson <awilliam@redhat.com> - 48.0-4
- Drop two x11-disablement-related backports to fix wayland sessions

* Fri May 30 2025 Neal Gompa <ngompa@fedoraproject.org> - 48.0-3
- Disable X11 for Fedora 43+ and RHEL

* Mon May 19 2025 Michel Lind <salimma@fedoraproject.org> - 48.0-2
- Disable X11 when building for EL10+
- Always install XWayland targets

* Mon Apr 21 2025 nmontero <nmontero@redhat.com> - 48.0-1
- Update to 48.0

* Thu Jan 16 2025 Fedora Release Engineering <releng@fedoraproject.org> - 47.0.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Sun Sep 22 2024 David King <amigadave@amigadave.com> - 47.0.1-1
- Update to 47.0.1

* Thu Jul 18 2024 Fedora Release Engineering <releng@fedoraproject.org> - 46.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Thu Mar 21 2024 David King <amigadave@amigadave.com> - 46.0-1
- Update to 46.0

* Wed Mar 06 2024 David King <amigadave@amigadave.com> - 46~rc-1
- Update to 46.rc

* Thu Feb 22 2024 Neal Gompa <ngompa@fedoraproject.org> - 46~alpha-2
- Mark the xsession subpackage as deprecated

* Wed Jan 31 2024 Nieves Montero <nmontero@redhat.com> - 46~alpha-1
- Update to 46~alpha

* Wed Jan 24 2024 Fedora Release Engineering <releng@fedoraproject.org> - 45.0-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Fri Jan 19 2024 Fedora Release Engineering <releng@fedoraproject.org> - 45.0-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Thu Jan 18 2024 Troy Dawson <tdawson@redhat.com> - 45.0-6
- Make i686 exclusion for RHEL only

* Mon Jan 15 2024 Troy Dawson <tdawson@redhat.com> - 45.0-5
- Re-enable i686 This is not a leaf package. Removing i686 affects too many
  other packages.

* Tue Jan 09 2024 Troy Dawson <tdawson@redhat.com> - 45.0-4
- Exclude i686

## END: Generated by rpmautospec
